# basic config file
seed: 1
record_video: yes
activation: tanh
on_cluster: True
learning_rate: 5e-4
use_adaptive_lr: False

environment:
  render: False
  num_envs: 120 #26
  eval_every_n: 1000 #200
  num_threads: 60 #30
  simulation_dt: 0.0025
  control_dt: 0.005
  max_time: 4.0
  reward:
    waypointDist:
      coeff: -1.0
    orientError:
      coeff: -1.0
    deltaOuzelRefPositionOffset:
      coeff: -1.0e-2
    orientRefCorr:
      coeff: -1.0e-2
    deltaJointAngles:
      coeff: -1.0e-2
    deltaJointAnglesClamp:
      coeff: -1.0e1
  termination:
    oob:
      reward: -1000.0
      waypointDist: 5.0
      angleErrorDeg: 60.0
    success:
      reward: 1000.0
      waypointDist: 0.05
      angleErrorDeg: 5.0
      linearVel: 0.01
      angularVelDeg: 0.1
  initialisation:
    distanceOffset: 1.5
    angleOffsetDeg: 45.0
    linearVel: 0.2
    angularVelDeg: 5.0
  controller:
    use_ext_wrench: 0.0
    x_gain: 1.0
    y_gain: 1.0
    z_gain: 1.0
    lin_p_gain: 20.0
    lin_i_gain: 0.0
    lin_d_gain: 5.0
    roll_gain: 1.0
    pitch_gain: 1.0
    yaw_gain: 0.5
    ang_p_gain: 35.0
    ang_i_gain: 0.0
    ang_d_gain: 12.0
    pos_err_max: 0.0
    max_linear_accel: 7.0
    max_angular_accel: 50.0
    position_integrator_limit: 1.0
    attitude_integrator_limit: 1.0
    tool_virtual_mass: 1.0
    base_virtual_mass: 1.0
    base_virtual_inertia: 1.0
    range_d_min: -0.1
    range_d_max: 0.1
    virtual_mass_decay: 0.1
    force_integrator_limit: 5.0
    force_p_gain: 0.1
    force_i_gain: 0.4
    use_force_control: 0
    vehicle_params: # from ouzel minimal
      mass: 4.58503
      inertia:
        xx: 0.0688659
        xy: 0.0
        xz: 0.0
        yy: 0.0430584
        yz: 0.0
        zz: 0.104985
      com_offset:
        x: 0.0
        y: 0.0
        z: 0.0
      gravity: 9.81
  imu: # from mav_tools/mav_description/urdf/ouzel_base.xacro
    accelerometerBiasCorrelationTime: 300.0
    accelerometerTurnOnBiasSigma: 0.1960
    accelerometerNoiseDensity: 0.004
    accelerometerRandomWalk: 0.006
    gyroscopeBiasCorrelationTime: 1000.0
    gyroscopeTurnOnBiasSigma: 0.0087
    gyroscopeNoiseDensity: 0.00005366563
    gyroscopeRandomWalk: 0.000038785
    linkName: ouzel/base_link
    robotNamespace: ouzel
  odometry:
    linkName: ouzel/base_link
    childFrameId: ouzel
  odometryNoise:
    pos_std: 1.0e-4
    orient_std: 1.0e-4
    lin_vel_std: 5.0e-3
    ang_vel_std: 5.0e-3
  deltaArm: #from delta_control/resources/delta_control_params_real.yaml
    r_B: 0.084
    r_T: 0.038
    l_P: 0.156
    l_D: 0.2499
    theta_min: 0.0
    theta_max: 1.5
    vel_p_gain: 10.0
    vel_i_gain: 0.0
    vel_d_gain: 0.0
    vel_ff_gain: 0.5
    # Dynamic params
    m_Base: 0.0
    m_O: 0.0
    m_A: 0.06
    m_P: 0.125
    I_Base:
      x: 0.0
      y: 0.0
      z: 0.0
    I_O:
      x: 0.0
      y: 0.0
      z: 0.0
    I_A:
      x: 0.000022
      y: 0.0008018
      z: 0.000817
    I_P:
      x: 0.0001368
      y: 0.0001439
      z: 0.0002548
    pCom_Base:
      x: 0.0
      y: 0.0
      z: 0.0
    pCom_O:
      x: 0.0
      y: 0.0
      z: 0.0
    pCom_A:
      x: 0.099
      y: 0.0
      z: 0.0
    pCom_P:
      x: 0.0
      y: 0.0
      z: 0.0016
    p_BO:
      x: -0.043
      y: 0.010
      z: -0.094
    q_BO:
      w: 0.00726273,
      x: 0.9999278,
      y: 0.00176325,
      z: 0.00940957

architecture:
  policy_net: [ 64, 64 ]
  value_net: [ 64, 64 ]
