<?xml version="1.0"?>

<robot name="$(arg mav_name)" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Properties -->
    <xacro:property name="manipulator_length" value="0.5"/>     <!-- [m] -->
    <xacro:property name="manipulator_radius" value="0.01"/>    <!-- [m] -->
    <xacro:property name="manipulator_mass" value="0.18"/>      <!-- [kg] -->
    <xacro:property name="tool_body_length" value="0.05"/>      <!-- [m] -->
    <xacro:property name="tool_body_mass" value="0.1"/>         <!-- [kg] -->
    <xacro:property name="tool_arm_length" value="0.05"/>       <!-- [m] -->
    <xacro:property name="tool_arm_radius" value="0.006"/>      <!-- [m] -->
    <xacro:property name="tool_arm_mass" value="0.1"/>          <!-- [kg] -->
    <xacro:property name="tool_wheelBig_radius" value="0.02"/>   <!-- [m] -->
    <xacro:property name="tool_wheelSmall_radius" value="0.015"/> <!-- [m] -->
    <xacro:property name="tool_wheelBig_length" value="0.02"/>   <!-- [m] -->
    <xacro:property name="tool_wheelSmall_length" value="0.02"/> <!-- [m] -->
    <xacro:property name="tool_wheelBig_mass" value="0.05"/>     <!-- [kg] -->
    <xacro:property name="tool_wheelSmall_mass" value="0.02"/>   <!-- [kg] -->

    <xacro:property name="mesh_file_concrete_sensor" value="package://mav_description/meshes/concrete_sensor_wout_wheels.stl" />
    <xacro:property name="mesh_file_concrete_sensor_wheel" value="package://mav_description/meshes/concrete_sensor_wheel.stl" />

    <!-- Add Ouzel frames -->
    <joint name="${namespace}/manipulator_joint" type="fixed">
        <axis xyz="0 0 1" />
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <parent link="${namespace}/base_link"/>
        <child link="${namespace}/manipulator"/>
    </joint>

    <link name="${namespace}/manipulator">
        <visual>
            <origin xyz="0 0 ${manipulator_length/2.0}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${manipulator_radius}" length="${manipulator_length}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${manipulator_length/2.0}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${manipulator_radius}" length="${manipulator_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${manipulator_mass}" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>
    <gazebo reference="${namespace}/manipulator">
        <material>Gazebo/Blue</material>
    </gazebo>

    <!-- Instantiate force sensor on end-effector -->
    <xacro:include filename="$(find mav_description)/urdf/manipulator_snippets.xacro"/>
    <xacro:force_sensor_plugin_macro
            namespace="${namespace}"
            force_sensor_suffix="tool"
            parent_link="${namespace}/manipulator"
            force_sensor_topic="force_sensor"
            force_sensor_truth_topic="force_sensor_truth"
            wrench_vector_pub_topic="wrench_vector"
            publish_frame_id="/${namespace}/force_sensor_tool"
            parent_frame_id="world"
            reference_frame_id="world"
            mass_force_sensor="0.1"
            lin_force_meas_enabled="true"
            torque_meas_enabled="false"
            disp_wrench_vector="true"
            measurement_divisor="1"
            measurement_delay="0"
            unknown_delay="0.0"
            cutoff_frequency="10.0"
            noise_normal_linear_force="0 0 0"
            noise_normal_torque="0 0 0"
            noise_uniform_linear_force="0 0 0"
            noise_uniform_torque="0 0 0" >
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
        <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
        <origin xyz="0.0 0.0 ${manipulator_length}" rpy="0.0 0.0 0.0"/>
    </xacro:force_sensor_plugin_macro>

    <joint name="${namespace}/tool_joint" type="revolute">
        <origin xyz="0.0 0.0 0.06" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/force_sensor_tool"/>
        <child link="${namespace}/concrete_sensor_tool"/>
        <limit upper="0" lower="0" effort="0" velocity="0" />
    </joint>

    <!-- Concrete Sensor Tool -->
    <link name="${namespace}/concrete_sensor_tool">
        <visual>
            <!--          <origin xyz="0.19 0.0 0.065" rpy="0. 4.7124 -0.1" />-->
            <!--          <origin xyz="0.023 -0.106 -0.09" rpy="0.0 4.7124 0.0" />-->
            <origin xyz="0.112 -0.022 -0.003" rpy="0.0 3.1416 -1.5708" />
            <geometry>
                <mesh filename="${mesh_file_concrete_sensor}"
                      scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.2 ${tool_body_length}" />
            </geometry>
            <!--          <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />-->
            <!--          <geometry>-->
            <!--              <cylinder length="0.18" radius="0.018" /> &lt;!&ndash; [m] &ndash;&gt;-->
            <!--          </geometry>-->
        </collision>
        <inertial>
            <mass value="0.1" />
            <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0005"/>
        </inertial>
    </link>
    <gazebo reference="${namespace}/concrete_sensor_tool">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Left arm-wheel   -->
    <joint name="${namespace}/tool_joint_L1" type="fixed">
        <origin xyz="0.0 -0.08 ${tool_body_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_tool"/>
        <child link="${namespace}/concrete_sensor_L"/>
    </joint>

    <link name="${namespace}/concrete_sensor_L">
        <collision>
            <origin xyz="0 0 ${tool_arm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${tool_arm_radius}" length="${tool_arm_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>

    <joint name="${namespace}/tool_joint_L2" type="fixed">
        <origin xyz="0.0 0.0 ${tool_arm_length}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_L"/>
        <child link="${namespace}/concrete_sensor_wheel_L"/>
    </joint>

    <link name="${namespace}/concrete_sensor_wheel_L">
        <visual>
            <origin xyz="0.096 -0.135 0.047" rpy="0.0 0.0 1.5708" />
            <geometry>
                <mesh filename="${mesh_file_concrete_sensor_wheel}"
                                      scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${tool_wheelSmall_length/2}" rpy="1.5708 0 0"/>
            <geometry>
                <cylinder radius="${tool_wheelSmall_radius}" length="${tool_wheelSmall_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${tool_wheelSmall_mass}" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>
    <gazebo reference="${namespace}/concrete_sensor_wheel_L">
        <material>Gazebo/Red</material>
    </gazebo>


    <!-- Central arm-wheel   -->
    <joint name="${namespace}/tool_joint_C1" type="fixed">
        <origin xyz="0.0 0.0 ${tool_body_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_tool"/>
        <child link="${namespace}/concrete_sensor_C"/>
    </joint>

    <link name="${namespace}/concrete_sensor_C">
        <collision>
            <origin xyz="0 0 ${tool_arm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${tool_arm_radius}" length="${tool_arm_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>

    <joint name="${namespace}/tool_joint_C2" type="fixed">
        <origin xyz="0.0 0.0 ${tool_arm_length}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_C"/>
        <child link="${namespace}/concrete_sensor_wheel_C"/>
    </joint>

    <link name="${namespace}/concrete_sensor_wheel_C">
        <collision>
            <origin xyz="0 0 ${tool_wheelBig_length/2}" rpy="1.5708 0 0"/>
            <geometry>
                <cylinder radius="${tool_wheelBig_radius}" length="${tool_wheelBig_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${tool_wheelBig_mass}" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>

    <!-- Right arm-wheel   -->
    <joint name="${namespace}/tool_joint_R1" type="fixed">
        <origin xyz="0.0 0.08 ${tool_body_length/2}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_tool"/>
        <child link="${namespace}/concrete_sensor_R"/>
    </joint>

    <link name="${namespace}/concrete_sensor_R">
        <collision>
            <origin xyz="0 0 ${tool_arm_length/2}" rpy="0 0 0"/>
            <geometry>
                <cylinder radius="${tool_arm_radius}" length="${tool_arm_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>

    <joint name="${namespace}/tool_joint_R2" type="fixed">
        <origin xyz="0.0 0.0 ${tool_arm_length}" rpy="0.0 0.0 0.0"/>
        <parent link="${namespace}/concrete_sensor_R"/>
        <child link="${namespace}/concrete_sensor_wheel_R"/>
    </joint>

    <link name="${namespace}/concrete_sensor_wheel_R">
        <visual>
<!--            <origin xyz="0.096 -0.135 0.047" rpy="0.0 0.0 -1.5708" />-->
            <origin xyz="-0.096 0.135 0.047" rpy="0.0 0.0 -1.5708" />
            <geometry>
                <mesh filename="${mesh_file_concrete_sensor_wheel}"
                      scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${tool_wheelSmall_length/2}" rpy="1.5708 0 0"/>
            <geometry>
                <cylinder radius="${tool_wheelSmall_radius}" length="${tool_wheelSmall_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="${tool_wheelSmall_mass}" />
            <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
        </inertial>
    </link>
    <gazebo reference="${namespace}/concrete_sensor_wheel_R">
        <material>Gazebo/Red</material>
    </gazebo>



</robot>