<?xml version="1.0" ?>
<!--
Model of cable connecting from a ground poaition to the ouzel
adapted from fire hose model: https://bitbucket.org/osrf/gazebo_models/src/de9abaab0588d76bc0e940dbdf0078b4bfe7b78a/fire_hose_long/?at=default
-->

<robot name="$(arg mav_name)" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="pi" value="3.14159265359"/>

  <xacro:macro name="cable_element" params="number length radius mass">
    <xacro:property name="inertia" value="${0.005*mass*50}"/>
    <link name="cable/link_${number}">
      <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
        <inertia
          ixx="${inertia}"
          ixy="0.00"
          ixz="0.00"
          iyy="${inertia}"
          iyz="0.00"
          izz="${inertia}"
        />
      </inertial>
      <visual>
        <origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder
            length="${length}"
            radius="${radius}"
          />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${-length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder
            length="${length}"
            radius="${radius}"
          />
        </geometry>
      </collision>
    </link>
  </xacro:macro>

  <xacro:macro name="cable_sphere" params="number subnumber radius mass length">
    <xacro:property name="inertia" value="${0.005*mass*50}"/>
    <link name="cable/sphere_${number}_${subnumber}">
      <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
          ixx="${inertia}"
          ixy="0.00"
          ixz="0.00"
          iyy="${inertia}"
          iyz="0.00"
          izz="${inertia}"
        />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere
            radius="${radius}"
          />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere
            radius="${radius}"
          />
        </geometry>
      </collision>
    </link>
    <gazebo reference="cable/sphere_${number}_${subnumber}">
      <turnGravityOff>true</turnGravityOff>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="cable_connection" params="number length radius mass ">
    <xacro:cable_sphere number="${number}" subnumber="1" radius="${radius}" mass="${mass}" length="${length}"/>
    <xacro:cable_sphere number="${number}" subnumber="2" radius="${radius}" mass="${mass}" length="${length}"/>

    <joint name="cable/cable_joint_${number}_x" type="revolute">
      <origin xyz="0 0 ${-length}" rpy="0 0 0" />
      <axis xyz="1 0 0"/>
      <limit upper="${pi / 3}" lower="${pi / -3}" effort="0" velocity="3" />
      <parent link="cable/link_${number-1}" />
      <child link="cable/sphere_${number}_1" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>

    <joint name="cable/cable_joint_${number}_y" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      <limit upper="${pi / 3}" lower="${pi / -3}" effort="0" velocity="3" />
      <parent link="cable/sphere_${number}_1" />
      <child link="cable/sphere_${number}_2" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>

    <joint name="cable/cable_joint_${number}_z" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
      <limit upper="${pi / 3}" lower="${pi / -3}" effort="0" velocity="3" />
      <parent link="cable/sphere_${number}_2" />
      <child link="cable/link_${number}" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>
  
  </xacro:macro>



<xacro:macro name="cable_generate" params="number resolution length radius mass">
  <xacro:unless value="${number == (resolution+1)}">
    <xacro:cable_element number="${number}" length="${length}" radius="${radius}" mass="${mass}"/>
    <xacro:cable_connection number="${number}" length="${length}" radius="${radius}" mass="${mass}"/>
    <xacro:cable_generate number="${number+1}" length="${length}" radius="${radius}" mass="${mass}" resolution="${resolution}"/>
  </xacro:unless>
</xacro:macro>


<xacro:macro name="cable_end" params="number subnumber radius mass">
  <link name="cable/sphere_${number}_${subnumber}">
      <inertial>
        <mass value="${mass}"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia
          ixx="0.0001"
          ixy="0.00"
          ixz="0.00"
          iyy="0.0001"
          iyz="0.00"
          izz="0.0001"
        />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere
            radius="${radius}"
          />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere
            radius="${radius}"
          />
        </geometry>
      </collision>
    </link>
    <gazebo reference="cable/sphere_${number}_${subnumber}">
      <turnGravityOff>true</turnGravityOff>
    </gazebo>
  </xacro:macro>





  <xacro:macro name="cable_add" params="length:=15 diameter:=0.05 mass:=1 end_z:=0.5 resolution:=5">
    <xacro:property name="length_element" value="${length/resolution}"/>
    <xacro:property name="radius" value="${diameter/2}"/>
    <xacro:property name="mass_element" value="${mass/resolution}"/>
    

    <joint name="${namespace}/base_cable_joint" type="revolute">
      <origin xyz="0 0 -0.069" rpy="${pi / 2} 0 0" />
      <axis xyz="1 0 0"/>
      <limit upper="0" lower="${-pi}" effort="0" velocity="3" />
      <parent link="${namespace}/base_link" />
      <child link="cable/sphere_1_1" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>

    <joint name="cable/cable_joint_1_y" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      <limit upper="${pi / 2}" lower="${pi / -2}" effort="0" velocity="3" />
      <parent link="cable/sphere_1_1" />
      <child link="cable/sphere_1_2" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>

    <joint name="cable/cable_joint_1_z" type="revolute">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
      <limit upper="${pi / 2}" lower="${pi / -2}" effort="0" velocity="3" />
      <parent link="cable/sphere_1_2" />
      <child link="cable/link_1" />
      <dynamics damping="0.03"/>
      <gazebo impicitSpringDamper="true"/>
    </joint>

    <xacro:cable_sphere number="1" subnumber="1" radius="${radius}" mass="${mass_element}" length="length_element"/>
    <xacro:cable_sphere number="1" subnumber="2" radius="${radius}" mass="${mass_element}" length="length_element"/>
    



    <xacro:cable_element number="1" length="${length_element}" radius="${radius}" mass="${mass_element}"/>

    <xacro:cable_generate number="2" length="${length_element}" radius="${radius}" mass="${mass_element}" resolution="${resolution}"/>




    <!-- fix cable end position with at end of cable with hight end_z-->
    

    <xacro:cable_end number="end" subnumber="1" radius="${radius}" mass="${mass_element}"/>
    <xacro:cable_end number="end" subnumber="2" radius="${radius}" mass="${mass_element}"/>

    <joint name="cable/cable_joint_end_x" type="continuous">
      <origin xyz="0 0 ${-length_element}" rpy="${-pi/2} 0 0" />
      <axis xyz="1 0 0"/>
      <parent link="cable/link_${resolution}" />
      <child link="cable/sphere_end_1" />
    </joint>

    <joint name="cable/cable_joint_end_y" type="continuous">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 1 0"/>
      <parent link="cable/sphere_end_1" />
      <child link="cable/sphere_end_2" />
    </joint>

    <joint name="cable/cable_joint_end_z" type="continuous">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <axis xyz="0 0 1"/>
      <parent link="cable/sphere_end_2" />
      <child link="cable/link_end" />
    </joint>

    <link name="cable/link_end">
      <pose> 1 1 0 0 0 0 </pose>
      <inertial>
        <mass value="100000"/>
        <origin xyz="0 0 ${-end_z/2}" rpy="0 0 0"/>
        <inertia
          ixx="100000"
          ixy="0.00"
          ixz="0.00"
          iyy="100000"
          iyz="0.00"
          izz="100000"
        />
      </inertial>
      <visual>
        <origin xyz="0 0 ${-end_z/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder
            length="${end_z}"
            radius="0.3"
          />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${-end_z/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder
            length="${end_z}"
            radius="1"
          />
        </geometry>
      </collision>
    </link>
    

   

  </xacro:macro>

</robot>
