<?xml version="1.0"?>

<robot name="$(arg mav_name)" xmlns:xacro="http://ros.org/wiki/xacro">

<!-- Properties -->
  <xacro:property name="manipulator_length" value="0.5"/>   <!-- [m] -->
  <xacro:property name="manipulator_radius" value="0.01"/>  <!-- [m] -->
  <xacro:property name="manipulator_mass" value="0.18"/>    <!-- [kg] -->
  <xacro:property name="tool_length" value="0.07"/>         <!-- [m] -->
  <xacro:property name="tool_radius" value="0.01"/>         <!-- [m] -->
  <xacro:property name="tool_mass" value="0.03"/>           <!-- [kg] -->

<!-- Add Ouzel frames -->
  <joint name="${namespace}/manipulator_joint" type="fixed">
      <axis xyz="0 0 1" />
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <parent link="${namespace}/base_link"/>
      <child link="${namespace}/manipulator"/>
  </joint>

  <link name="${namespace}/manipulator">
    <visual>
      <origin xyz="0 0 ${manipulator_length/2.0}" rpy="0 0 0"/>
      <geometry>
          <cylinder radius="${manipulator_radius}" length="${manipulator_length}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${manipulator_length/2.0}" rpy="0 0 0"/>
      <geometry>
          <cylinder radius="${manipulator_radius}" length="${manipulator_length}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="${manipulator_mass}" />
      <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
    </inertial>
  </link>
  <gazebo reference="${namespace}/manipulator">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- Instantiate force sensor on end-effector -->
  <xacro:include filename="$(find mav_description)/urdf/manipulator_snippets.xacro"/>
  <xacro:force_sensor_plugin_macro
    namespace="${namespace}"
    force_sensor_suffix="tool"
    parent_link="${namespace}/manipulator"
    force_sensor_topic="force_sensor"
    force_sensor_truth_topic="force_sensor_truth"
    wrench_vector_pub_topic="wrench_vector"
    publish_frame_id="/${namespace}/force_sensor_tool"
    parent_frame_id="world"
    reference_frame_id="world"
    mass_force_sensor="0.1"
    lin_force_meas_enabled="true"
    torque_meas_enabled="false"
    disp_wrench_vector="true"
    measurement_divisor="1"
    measurement_delay="0"
    unknown_delay="0.0"
    cutoff_frequency="10.0"
    noise_normal_linear_force="0 0 0"
    noise_normal_torque="0 0 0"
    noise_uniform_linear_force="0 0 0"
    noise_uniform_torque="0 0 0" >
    <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    <!-- [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] [kg m^2] -->
    <origin xyz="0.0 0.0 ${manipulator_length}" rpy="0.0 0.0 0.0"/>
  </xacro:force_sensor_plugin_macro>

  <joint name="${namespace}/tool_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 0" rpy="0.0 0.0 0.0"/>
    <parent link="${namespace}/force_sensor_tool"/>
    <child link="${namespace}/tool"/>
  </joint>

  <link name="${namespace}/tool">
    <visual>
        <origin xyz="0 0 ${tool_length/2.0}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${tool_radius}" length="${tool_length}" />
        </geometry>
    </visual>
    <collision>
        <origin xyz="0 0 ${tool_length/2.0}" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${tool_radius}" length="${tool_length}" />
        </geometry>
    </collision>
    <inertial>
      <mass value="${tool_mass}" />
      <inertia ixx="0.000807" ixy="0" ixz="0" iyy="0.000807" iyz="0" izz="2e-6"/>
    </inertial>
  </link>
  <gazebo reference="${namespace}/tool">
    <material>Gazebo/Black</material>
  </gazebo>

</robot>
